# Generated by Django 4.1.7 on 2023-03-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipkemboi', '0002_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.IntegerField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
