# Generated by Django 4.1.7 on 2023-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipkemboi', '0004_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
